# Use this environment to run `detection/run_tf_detector*.py`
# If your computer does not have a CUDA-supported GPU, change the
# dependency `tensorflow-gpu` to `tensorflow`

name: tf2_camtrap

dependencies:
- python>=3.6
- nb_conda_kernels
- ipykernel
- tqdm
- jsonpickle
- Pillow>=5.3.0
- humanfriendly
- numpy
- matplotlib
- nb_conda_kernels
- ipykernel

# the `nb_conda_kernels` and `ipykernel` packages are installed so that we
# can use Jupyter Notebooks with this environment as a kernel